apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: fahds1993/hello-go:v3
          ports:
            - containerPort: 8080
          env:
            - name: NAME
              value: "Fábio"
            - name: AGE
              value: "32"